apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hello-world-go-shipwright-example
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hello-world-go-shipwright-example
    app.kubernetes.io/part-of: shipwright-example
  name: hello-world-go-shipwright-example
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: hello-world-go-shipwright-example
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: hello-world-go-shipwright-example
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jkhelil-tenant/shipwright-example/hello-world-go-shipwright-example@sha256:7e2db4398cdc3e916b1f8dc4e176f3a7c48f00f46891a216838c8a810f0c0b63
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
