apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hello-world-go-shipwright-example
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hello-world-go-shipwright-example
    app.kubernetes.io/part-of: shipwright-example
  name: hello-world-go-shipwright-example
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: hello-world-go-shipwright-example
status:
  loadBalancer: {}
