apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hello-world-go-shipwright-example
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hello-world-go-shipwright-example
    app.kubernetes.io/part-of: shipwright-example
  name: hello-world-go-shipwright2iqp
spec:
  path: /
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: hello-world-go-shipwright-example
    weight: null
status: {}
